import type { Metadata } from "next";

import "@/styles/globals.css";

import { SWRProvider } from "@/libs";
import { CategoryTab, Header, SideNavBar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CATEGORYS = ["육군", "해군", "공군", "해병대"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SWRProvider>
          <div className="w-full h-screen flex bg-primary">
            <SideNavBar />

            <article className="flex-1 max-w-[1478px] mx-auto pl-12 pr-20  overflow-auto">
              <Header />
              <nav className="flex gap-3 my-14">
                {CATEGORYS.map((category) => (
                  <CategoryTab label={category} key={category} />
                ))}
              </nav>
              {children}
            </article>
          </div>
        </SWRProvider>
      </body>
    </html>
  );
}
